/******************************************************
 * Processor Module Implementation File.              *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "riscv.H"
#include  "riscv_isa.cpp"

#include  "riscv_syscall.H"

void* riscv::dispatch() {
  //!Updating Regs for behavioral simulation.
  if (ac_qk.need_sync()) {
    ac_qk.sync();
  }
  if( ac_pc >= dec_cache_size){
    cerr << "ArchC: Address out of bounds (pc=0x" << hex << ac_pc << ")." << endl;
    stop();
    longjmp(ac_env, AC_ACTION_STOP);
  }
  ac_instr_counter++;
  unsigned ins_id;
  instr_dec = (DEC_CACHE + (ac_pc));
  if ( !instr_dec->valid ){
    unsigned* ins_cache;
    decode_pc = ac_pc;
    quant = 0;
    ins_cache = (ISA.decoder)->Decode(reinterpret_cast<unsigned char*>(buffer), quant);
    instr_dec->valid = true;
    instr_dec->id = ins_cache ? ins_cache[IDENT]: 0;
    instr_dec->end_rot = IntRoutine[instr_dec->id];
    switch (ISA.instr_format_table[instr_dec->id]) {
      case 1:
        instr_dec->F_Type_R.funct7 = ins_cache[1];
        instr_dec->F_Type_R.funct5 = ins_cache[2];
        instr_dec->F_Type_R.aq = ins_cache[3];
        instr_dec->F_Type_R.rl = ins_cache[4];
        instr_dec->F_Type_R.rs2 = ins_cache[5];
        instr_dec->F_Type_R.rs1 = ins_cache[6];
        instr_dec->F_Type_R.funct3 = ins_cache[7];
        instr_dec->F_Type_R.rd = ins_cache[8];
        instr_dec->F_Type_R.op = ins_cache[9];
      break;
      case 2:
        instr_dec->F_Type_R4.rs3 = ins_cache[2];
        instr_dec->F_Type_R4.funct2 = ins_cache[10];
        instr_dec->F_Type_R4.rs2 = ins_cache[5];
        instr_dec->F_Type_R4.rs1 = ins_cache[6];
        instr_dec->F_Type_R4.funct3 = ins_cache[7];
        instr_dec->F_Type_R4.rd = ins_cache[8];
        instr_dec->F_Type_R4.op = ins_cache[9];
      break;
      case 3:
        instr_dec->F_Type_I.imm4 = ins_cache[11];
        instr_dec->F_Type_I.imm3 = ins_cache[12];
        instr_dec->F_Type_I.imm2 = ins_cache[13];
        instr_dec->F_Type_I.imm1 = ins_cache[14];
        instr_dec->F_Type_I.imm8 = ins_cache[15];
        instr_dec->F_Type_I.imm7 = ins_cache[16];
        instr_dec->F_Type_I.imm6 = ins_cache[17];
        instr_dec->F_Type_I.csr = ins_cache[18];
        instr_dec->F_Type_I.rs1 = ins_cache[6];
        instr_dec->F_Type_I.funct3 = ins_cache[7];
        instr_dec->F_Type_I.rd = ins_cache[8];
        instr_dec->F_Type_I.op = ins_cache[9];
      break;
      case 4:
        instr_dec->F_Type_S.imm4 = ins_cache[11];
        instr_dec->F_Type_S.imm3 = ins_cache[12];
        instr_dec->F_Type_S.rs2 = ins_cache[5];
        instr_dec->F_Type_S.rs1 = ins_cache[6];
        instr_dec->F_Type_S.funct3 = ins_cache[7];
        instr_dec->F_Type_S.imm2 = ins_cache[19];
        instr_dec->F_Type_S.imm1 = ins_cache[20];
        instr_dec->F_Type_S.op = ins_cache[9];
      break;
      case 5:
        instr_dec->F_Type_SB.imm4 = ins_cache[11];
        instr_dec->F_Type_SB.imm2 = ins_cache[12];
        instr_dec->F_Type_SB.rs2 = ins_cache[5];
        instr_dec->F_Type_SB.rs1 = ins_cache[6];
        instr_dec->F_Type_SB.funct3 = ins_cache[7];
        instr_dec->F_Type_SB.imm1 = ins_cache[19];
        instr_dec->F_Type_SB.imm3 = ins_cache[20];
        instr_dec->F_Type_SB.op = ins_cache[9];
      break;
      case 6:
        instr_dec->F_Type_U.imm = ins_cache[21];
        instr_dec->F_Type_U.rd = ins_cache[8];
        instr_dec->F_Type_U.op = ins_cache[9];
      break;
      case 7:
        instr_dec->F_Type_UJ.imm4 = ins_cache[11];
        instr_dec->F_Type_UJ.imm1 = ins_cache[22];
        instr_dec->F_Type_UJ.imm2 = ins_cache[14];
        instr_dec->F_Type_UJ.imm3 = ins_cache[23];
        instr_dec->F_Type_UJ.rd = ins_cache[8];
        instr_dec->F_Type_UJ.op = ins_cache[9];
      break;
      default:
        cerr << "ArchC Error: Unidentified instruction. " << endl;
        cerr << "PC = " << hex << ac_pc << dec << endl;
        stop();
        longjmp(ac_env, AC_ACTION_STOP);
    }
  }
  ins_id = instr_dec->id;

  ISA.cur_instr_id = ins_id;
  return instr_dec->end_rot;
}

void riscv::behavior() {

  void* vet[] = {&&I_Init, &&I_ADD, &&I_SUB, &&I_SLL, &&I_SLT, 
              &&I_SLTU, &&I_XOR, &&I_SRL, &&I_SRA, &&I_OR, 
              &&I_AND, &&I_LB, &&I_LH, &&I_LW, &&I_LBU, 
              &&I_LHU, &&I_ADDI, &&I_SLTI, &&I_SLTIU, &&I_XORI, 
              &&I_ORI, &&I_ANDI, &&I_JALR, &&I_SLLI, &&I_SRLI, 
              &&I_SRAI, &&I_SCALL, &&I_SBREAK, &&I_RDCYCLE, &&I_RDCYCLEH, 
              &&I_RDTIME, &&I_RDTIMEH, &&I_RDINSTRET, &&I_RDINSTRETH, &&I_FENCE, 
              &&I_FENCE_I, &&I_CSRRS, &&I_CSRRW, &&I_CSRRC, &&I_SB, 
              &&I_SH, &&I_SW, &&I_BEQ, &&I_BNE, &&I_BLT, 
              &&I_BGE, &&I_BLTU, &&I_BGEU, &&I_LUI, &&I_AUIPC, 
              &&I_JAL, &&I_MUL, &&I_MULH, &&I_MULHSU, &&I_MULHU, 
              &&I_DIV, &&I_DIVU, &&I_REM, &&I_REMU, &&I_LR_W, 
              &&I_SC_W, &&I_AMOSWAP_W, &&I_AMOADD_W, &&I_AMOXOR_W, &&I_AMOAND_W, 
              &&I_AMOOR_W, &&I_AMOMIN_W, &&I_AMOMAX_W, &&I_AMOMINU_W, &&I_AMOMAXU_W, 
              &&I_FLW, &&I_FSW, &&I_FADD_S, &&I_FSUB_S, &&I_FMUL_S, 
              &&I_FDIV_S, &&I_FMIN_S, &&I_FMAX_S, &&I_FSQRT_S, &&I_FMADD_S, 
              &&I_FMSUB_S, &&I_FNMSUB_S, &&I_FNMADD_S, &&I_FCVT_W_S, &&I_FCVT_WU_S, 
              &&I_FCVT_S_WU, &&I_FCVT_S_W, &&I_FSGNJN_S, &&I_FSGNJ_S, &&I_FSGNJX_S, 
              &&I_FMV_X_S, &&I_FMV_S_X, &&I_FEQ_S, &&I_FLT_S, &&I_FLE_S, 
              &&I_FMV_S, &&I_FLD, &&I_FSD, &&I_FADD_D, &&I_FSUB_D, 
              &&I_FMUL_D, &&I_FDIV_D, &&I_FMIN_D, &&I_FMAX_D, &&I_FSQRT_D, 
              &&I_FMADD_D, &&I_FMSUB_D, &&I_FNMSUB_D, &&I_FNMADD_D, &&I_FCVT_S_D, 
              &&I_FCVT_D_S, &&I_FCVT_W_D, &&I_FCVT_WU_D, &&I_FCVT_D_W, &&I_FCVT_D_WU, 
              &&I_FSGNJ_D, &&I_FSGNJN_D, &&I_FSGNJX_D, &&I_FMV_D, &&I_FEQ_D, 
              &&I_FLT_D, &&I_FLE_D};

  IntRoutine = vet;

  if (has_delayed_load) {
    DM_mport.load(delayed_load_program);
    ac_pc = ac_start_addr;
    has_delayed_load = false;
  }

  #define AC_SYSC(NAME,LOCATION) \
  instr_dec = (DEC_CACHE + (LOCATION)); \
  instr_dec->valid = true; \
  instr_dec->id = 0; \
  instr_dec->end_rot = &&Sys_##LOCATION;

  #include <ac_syscall.def>
  #undef AC_SYSC

  int action = setjmp(ac_env);
  if (action == AC_ACTION_STOP) return;

  I_Init:
    goto *dispatch();

  #define AC_SYSC(NAME,LOCATION) \
  Sys_##LOCATION: \
    ISA.syscall.NAME(); \
    goto *dispatch();

  #include <ac_syscall.def>
  #undef AC_SYSC

  I_ADD: // Instruction ADD
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_ADD(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SUB: // Instruction SUB
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SUB(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SLL: // Instruction SLL
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SLL(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SLT: // Instruction SLT
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SLT(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SLTU: // Instruction SLTU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SLTU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_XOR: // Instruction XOR
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_XOR(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SRL: // Instruction SRL
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SRL(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SRA: // Instruction SRA
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SRA(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_OR: // Instruction OR
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_OR(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AND: // Instruction AND
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AND(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LB: // Instruction LB
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_LB(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LH: // Instruction LH
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_LH(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LW: // Instruction LW
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_LW(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LBU: // Instruction LBU
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_LBU(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LHU: // Instruction LHU
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_LHU(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ADDI: // Instruction ADDI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_ADDI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SLTI: // Instruction SLTI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SLTI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SLTIU: // Instruction SLTIU
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SLTIU(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_XORI: // Instruction XORI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_XORI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ORI: // Instruction ORI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_ORI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_ANDI: // Instruction ANDI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_ANDI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_JALR: // Instruction JALR
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_JALR(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SLLI: // Instruction SLLI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SLLI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SRLI: // Instruction SRLI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SRLI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SRAI: // Instruction SRAI
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SRAI(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SCALL: // Instruction SCALL
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SCALL(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SBREAK: // Instruction SBREAK
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_SBREAK(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_RDCYCLE: // Instruction RDCYCLE
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_RDCYCLE(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_RDCYCLEH: // Instruction RDCYCLEH
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_RDCYCLEH(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_RDTIME: // Instruction RDTIME
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_RDTIME(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_RDTIMEH: // Instruction RDTIMEH
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_RDTIMEH(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_RDINSTRET: // Instruction RDINSTRET
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_RDINSTRET(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_RDINSTRETH: // Instruction RDINSTRETH
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_RDINSTRETH(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FENCE: // Instruction FENCE
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_FENCE(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FENCE_I: // Instruction FENCE_I
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_FENCE_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_CSRRS: // Instruction CSRRS
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_CSRRS(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_CSRRW: // Instruction CSRRW
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_CSRRW(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_CSRRC: // Instruction CSRRC
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_CSRRC(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SB: // Instruction SB
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_riscv_Type_S(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ISA.behavior_SB(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SH: // Instruction SH
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_riscv_Type_S(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ISA.behavior_SH(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SW: // Instruction SW
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_riscv_Type_S(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ISA.behavior_SW(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_BEQ: // Instruction BEQ
    ISA._behavior_instruction(instr_dec->F_Type_SB.op);
    ISA._behavior_riscv_Type_SB(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ISA.behavior_BEQ(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_BNE: // Instruction BNE
    ISA._behavior_instruction(instr_dec->F_Type_SB.op);
    ISA._behavior_riscv_Type_SB(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ISA.behavior_BNE(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_BLT: // Instruction BLT
    ISA._behavior_instruction(instr_dec->F_Type_SB.op);
    ISA._behavior_riscv_Type_SB(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ISA.behavior_BLT(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_BGE: // Instruction BGE
    ISA._behavior_instruction(instr_dec->F_Type_SB.op);
    ISA._behavior_riscv_Type_SB(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ISA.behavior_BGE(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_BLTU: // Instruction BLTU
    ISA._behavior_instruction(instr_dec->F_Type_SB.op);
    ISA._behavior_riscv_Type_SB(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ISA.behavior_BLTU(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_BGEU: // Instruction BGEU
    ISA._behavior_instruction(instr_dec->F_Type_SB.op);
    ISA._behavior_riscv_Type_SB(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ISA.behavior_BGEU(instr_dec->F_Type_SB.imm4, instr_dec->F_Type_SB.imm2, instr_dec->F_Type_SB.rs2, instr_dec->F_Type_SB.rs1, instr_dec->F_Type_SB.funct3, instr_dec->F_Type_SB.imm1, instr_dec->F_Type_SB.imm3, instr_dec->F_Type_SB.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LUI: // Instruction LUI
    ISA._behavior_instruction(instr_dec->F_Type_U.op);
    ISA._behavior_riscv_Type_U(instr_dec->F_Type_U.imm, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    ISA.behavior_LUI(instr_dec->F_Type_U.imm, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AUIPC: // Instruction AUIPC
    ISA._behavior_instruction(instr_dec->F_Type_U.op);
    ISA._behavior_riscv_Type_U(instr_dec->F_Type_U.imm, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    ISA.behavior_AUIPC(instr_dec->F_Type_U.imm, instr_dec->F_Type_U.rd, instr_dec->F_Type_U.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_JAL: // Instruction JAL
    ISA._behavior_instruction(instr_dec->F_Type_UJ.op);
    ISA._behavior_riscv_Type_UJ(instr_dec->F_Type_UJ.imm4, instr_dec->F_Type_UJ.imm1, instr_dec->F_Type_UJ.imm2, instr_dec->F_Type_UJ.imm3, instr_dec->F_Type_UJ.rd, instr_dec->F_Type_UJ.op);
    ISA.behavior_JAL(instr_dec->F_Type_UJ.imm4, instr_dec->F_Type_UJ.imm1, instr_dec->F_Type_UJ.imm2, instr_dec->F_Type_UJ.imm3, instr_dec->F_Type_UJ.rd, instr_dec->F_Type_UJ.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_MUL: // Instruction MUL
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_MUL(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_MULH: // Instruction MULH
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_MULH(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_MULHSU: // Instruction MULHSU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_MULHSU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_MULHU: // Instruction MULHU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_MULHU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_DIV: // Instruction DIV
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_DIV(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_DIVU: // Instruction DIVU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_DIVU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_REM: // Instruction REM
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_REM(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_REMU: // Instruction REMU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_REMU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_LR_W: // Instruction LR_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_LR_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_SC_W: // Instruction SC_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_SC_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOSWAP_W: // Instruction AMOSWAP_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOSWAP_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOADD_W: // Instruction AMOADD_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOADD_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOXOR_W: // Instruction AMOXOR_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOXOR_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOAND_W: // Instruction AMOAND_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOAND_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOOR_W: // Instruction AMOOR_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOOR_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOMIN_W: // Instruction AMOMIN_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOMIN_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOMAX_W: // Instruction AMOMAX_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOMAX_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOMINU_W: // Instruction AMOMINU_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOMINU_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_AMOMAXU_W: // Instruction AMOMAXU_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_AMOMAXU_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FLW: // Instruction FLW
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_FLW(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSW: // Instruction FSW
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_riscv_Type_S(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ISA.behavior_FSW(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FADD_S: // Instruction FADD_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FADD_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSUB_S: // Instruction FSUB_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSUB_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMUL_S: // Instruction FMUL_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMUL_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FDIV_S: // Instruction FDIV_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FDIV_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMIN_S: // Instruction FMIN_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMIN_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMAX_S: // Instruction FMAX_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMAX_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSQRT_S: // Instruction FSQRT_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSQRT_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMADD_S: // Instruction FMADD_S
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FMADD_S(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMSUB_S: // Instruction FMSUB_S
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FMSUB_S(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FNMSUB_S: // Instruction FNMSUB_S
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FNMSUB_S(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FNMADD_S: // Instruction FNMADD_S
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FNMADD_S(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_W_S: // Instruction FCVT_W_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_W_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_WU_S: // Instruction FCVT_WU_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_WU_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_S_WU: // Instruction FCVT_S_WU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_S_WU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_S_W: // Instruction FCVT_S_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_S_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSGNJN_S: // Instruction FSGNJN_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSGNJN_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSGNJ_S: // Instruction FSGNJ_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSGNJ_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSGNJX_S: // Instruction FSGNJX_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSGNJX_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMV_X_S: // Instruction FMV_X_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMV_X_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMV_S_X: // Instruction FMV_S_X
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMV_S_X(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FEQ_S: // Instruction FEQ_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FEQ_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FLT_S: // Instruction FLT_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FLT_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FLE_S: // Instruction FLE_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FLE_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMV_S: // Instruction FMV_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMV_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FLD: // Instruction FLD
    ISA._behavior_instruction(instr_dec->F_Type_I.op);
    ISA._behavior_riscv_Type_I(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ISA.behavior_FLD(instr_dec->F_Type_I.imm4, instr_dec->F_Type_I.imm3, instr_dec->F_Type_I.imm2, instr_dec->F_Type_I.imm1, instr_dec->F_Type_I.imm8, instr_dec->F_Type_I.imm7, instr_dec->F_Type_I.imm6, instr_dec->F_Type_I.csr, instr_dec->F_Type_I.rs1, instr_dec->F_Type_I.funct3, instr_dec->F_Type_I.rd, instr_dec->F_Type_I.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSD: // Instruction FSD
    ISA._behavior_instruction(instr_dec->F_Type_S.op);
    ISA._behavior_riscv_Type_S(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ISA.behavior_FSD(instr_dec->F_Type_S.imm4, instr_dec->F_Type_S.imm3, instr_dec->F_Type_S.rs2, instr_dec->F_Type_S.rs1, instr_dec->F_Type_S.funct3, instr_dec->F_Type_S.imm2, instr_dec->F_Type_S.imm1, instr_dec->F_Type_S.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FADD_D: // Instruction FADD_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FADD_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSUB_D: // Instruction FSUB_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSUB_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMUL_D: // Instruction FMUL_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMUL_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FDIV_D: // Instruction FDIV_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FDIV_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMIN_D: // Instruction FMIN_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMIN_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMAX_D: // Instruction FMAX_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMAX_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSQRT_D: // Instruction FSQRT_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSQRT_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMADD_D: // Instruction FMADD_D
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FMADD_D(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMSUB_D: // Instruction FMSUB_D
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FMSUB_D(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FNMSUB_D: // Instruction FNMSUB_D
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FNMSUB_D(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FNMADD_D: // Instruction FNMADD_D
    ISA._behavior_instruction(instr_dec->F_Type_R4.op);
    ISA._behavior_riscv_Type_R4(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ISA.behavior_FNMADD_D(instr_dec->F_Type_R4.rs3, instr_dec->F_Type_R4.funct2, instr_dec->F_Type_R4.rs2, instr_dec->F_Type_R4.rs1, instr_dec->F_Type_R4.funct3, instr_dec->F_Type_R4.rd, instr_dec->F_Type_R4.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_S_D: // Instruction FCVT_S_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_S_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_D_S: // Instruction FCVT_D_S
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_D_S(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_W_D: // Instruction FCVT_W_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_W_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_WU_D: // Instruction FCVT_WU_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_WU_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_D_W: // Instruction FCVT_D_W
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_D_W(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FCVT_D_WU: // Instruction FCVT_D_WU
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FCVT_D_WU(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSGNJ_D: // Instruction FSGNJ_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSGNJ_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSGNJN_D: // Instruction FSGNJN_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSGNJN_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FSGNJX_D: // Instruction FSGNJX_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FSGNJX_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FMV_D: // Instruction FMV_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FMV_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FEQ_D: // Instruction FEQ_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FEQ_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FLT_D: // Instruction FLT_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FLT_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

  I_FLE_D: // Instruction FLE_D
    ISA._behavior_instruction(instr_dec->F_Type_R.op);
    ISA._behavior_riscv_Type_R(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ISA.behavior_FLE_D(instr_dec->F_Type_R.funct7, instr_dec->F_Type_R.funct5, instr_dec->F_Type_R.aq, instr_dec->F_Type_R.rl, instr_dec->F_Type_R.rs2, instr_dec->F_Type_R.rs1, instr_dec->F_Type_R.funct3, instr_dec->F_Type_R.rd, instr_dec->F_Type_R.op);
    ac_qk.inc(time_1cycle);
    goto *dispatch();

} // behavior()

#include <ac_sighandlers.H>
#include <ac_args.H>

void riscv::init() {

#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void riscv::init(int ac, char *av[]) {

  args_t args = ac_init_args( ac, av);
  set_args(args.size, args.app_args);
  DM_mport.load(args.app_filename);
#ifdef AC_VERIFY
  set_queue(av[0]);
#endif

  ac_pc = ac_start_addr;
  ISA._behavior_begin();
  cerr << endl << "ArchC: -------------------- Starting Simulation --------------------" << endl;
  InitStat();
  start_up = 0;
  init_dec_cache();
  signal(SIGINT, sigint_handler);
  signal(SIGTERM, sigint_handler);
  signal(SIGSEGV, sigsegv_handler);
  signal(SIGUSR1, sigusr1_handler);
#ifdef USE_GDB
  signal(SIGUSR2, sigusr2_handler);
#endif
  set_running();
}

void riscv::set_prog_args(){
  ISA.syscall.set_prog_args(argc, argv);
}

//Stop simulation (may receive exit status)
void riscv::stop(int status) {
  cerr << endl << "ArchC: -------------------- Simulation Finished --------------------" << endl;
  ISA._behavior_end();
  ac_stop_flag = 1;
  ac_exit_status = status;
  set_stopped();
  longjmp(ac_env, AC_ACTION_STOP);
}

void riscv::load(char* program) {
  DM_mport.load(program);
}

void riscv::delayed_load(char* program) {
  has_delayed_load = true;
  delayed_load_program = new char[strlen(program)];
  strcpy(delayed_load_program, program);
}

// Returns ac_pc value
unsigned riscv::get_ac_pc() {
  return ac_pc;
}

// Assigns value to ac_pc
void riscv::set_ac_pc(unsigned int value) {
  ac_pc = value;
}

// Wrapper function to PrintStat().
void riscv::PrintStat() {
  ac_arch<riscv_parms::ac_word, riscv_parms::ac_Hword>::PrintStat();
}

// Assigns value to processor frequency and updates cycle time values
void riscv::set_proc_freq(unsigned int proc_freq) {
  ac_module::set_proc_freq(proc_freq);
  time_1cycle=sc_time(1*module_period_ns, SC_NS);
}

