/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "riscv_arch.H"


riscv_arch::riscv_arch() :
  ac_arch_dec_if<riscv_parms::ac_word, riscv_parms::ac_Hword>(riscv_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  ac_id("ac_id", 0),
  DM("DM", 536870912U),
  DM_mport(*this, DM),
  RB("RB"),
  RBF("RBF"),
  fflags("fflags", 0),
  frm("frm", 0),
  fcsr("fcsr", 0) {

  ac_mt_endian = riscv_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = riscv_parms::AC_PROC_ENDIAN;

  INST_PORT = &DM_mport;
  DATA_PORT = &DM_mport;
}

int riscv_arch::globalId = 0;